services:
  - type: web
    name: converter-mp4-playlist-to-mp3
    env: node
    buildCommand: |
      npm install
      pip install yt-dlp
      apt-get update
      apt-get install -y ffmpeg
    startCommand: node server/index.js